In [1]:
!ls

Algorithms.ipynb             integer-float-boolean.ipynb
JupyterNotebookAwesome.ipynb linked-list.ipynb
README.md                    list.ipynb
Recursion.ipynb              loop.ipynb
binary-tree.ipynb            queue.ipynb
built-in-function.ipynb      set.ipynb
dictionary.ipynb             stack.ipynb
function.ipynb               string.ipynb
graph.ipynb                  tree.ipynb
heap.ipynb                   tuple.ipynb


## 3D

In [2]:
!pip3 install ipyvolume

     |████████████████████████████████| 2.9MB 2.9MB/s eta 0:00:01
     |████████████████████████████████| 61kB 6.6MB/s eta 0:00:011
     |████████████████████████████████| 1.1MB 7.0MB/s eta 0:00:01
     |████████████████████████████████| 4.2MB 2.7MB/s eta 0:00:01     |██▍                             | 317kB 2.7MB/s eta 0:00:02     |████▉                           | 634kB 2.7MB/s eta 0:00:02     |████████████████████████▊       | 3.3MB 2.7MB/s eta 0:00:01     |████████████████████████████████| 4.2MB 2.7MB/s 
     |████████████████████████████████| 15.2MB 3.5MB/s eta 0:00:01    |██████████████████▊             | 8.9MB 2.5MB/s eta 0:00:03
     |████████████████████████████████| 2.1MB 8.2MB/s eta 0:00:01
     |████████████████████████████████| 61kB 17.2MB/s eta 0:00:01
  Using cached https://files.pythonhosted.org/packages/e8/74/6e4f91745020f967d09332bb2b8b9b10090957334692eb88ea4afe91b77f/urllib3-1.25.8-py2.py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/b9/63/df50c

You should consider upgrading via the 'pip install --upgrade pip' command.


In [6]:
import ipyvolume as ipv
import numpy as np

In [7]:
N = 1000

In [43]:
import ipyvolume as ipv
import numpy as np
x, y, z = np.random.random((3, 1))
ipv.quickscatter(x, y, z, size=1, marker="sphere")

In [44]:
x

array([0.35248597])

In [45]:
y

array([0.2537852])

In [41]:
x

array([0.19635043, 0.12657668, 0.86282728, ..., 0.48181048, 0.59047497,
       0.01604663])

In [36]:
fig = ipv.figure()
ipv.quiver(x, y, z, x, y, z, size=1, marker="sphere")
ipv.show()

In [33]:
ipv.save("index.html")

In [18]:
# f(u, v) -> (u, v, u*v**2)
a = np.arange(-5, 5)
U, V = np.meshgrid(a, a)
X = U
Y = V
Z = X**3

ipv.figure()
ipv.plot_surface(X, Z, Y, color="orange")
ipv.plot_wireframe(X, Z, Y, color="red")
ipv.show()

In [46]:
x, y, z, u, v, w = np.random.random((6, 1000))*2-1


In [47]:
x

array([ 0.45325037,  0.89015119,  0.1991896 ,  0.34025324, -0.7301398 ,
       -0.46920411, -0.47233456, -0.59520118,  0.40408152,  0.02972971,
       -0.2930181 ,  0.46273107,  0.69899336,  0.86406597, -0.89067884,
        0.65081751, -0.54255483,  0.43872944,  0.99382266,  0.70961163,
       -0.94478691,  0.37134523, -0.99772892, -0.48342542, -0.32572083,
       -0.06445356, -0.06576571,  0.62599209,  0.07793774, -0.06684187,
        0.92327135, -0.20803279, -0.94991059, -0.74704934,  0.52159105,
       -0.81758084, -0.69800427, -0.19302312,  0.84087765, -0.78338824,
        0.35863129,  0.26045042,  0.81748205, -0.43550213,  0.67554429,
       -0.56179015, -0.01615352,  0.21032537, -0.80557486, -0.04218608,
        0.00672699, -0.79045231,  0.10663257,  0.01668787,  0.36724626,
       -0.52912574, -0.90257715,  0.76518189, -0.98507459, -0.61418883,
       -0.50695207,  0.9052027 ,  0.7082764 ,  0.74578565,  0.10598051,
        0.5407364 , -0.82015447,  0.99779341,  0.35055269,  0.86

In [50]:
import ipyvolume as ipv
import numpy as np
x, y, z, u, v, w, i, j, k = np.random.random((9, 1000))*2-1
selected = np.random.randint(0, 1000, 100)
ipv.figure()
quiver = ipv.quiver(x, y, z, u, v, w, i, j, k, size=5, size_selected=8, selected=selected)

from ipywidgets import FloatSlider, ColorPicker, VBox, jslink
size = FloatSlider(min=0, max=30, step=0.1)
size_selected = FloatSlider(min=0, max=30, step=0.1)
color = ColorPicker()
color_selected = ColorPicker()
jslink((quiver, 'size'), (size, 'value'))
jslink((quiver, 'size_selected'), (size_selected, 'value'))
jslink((quiver, 'color'), (color, 'value'))
jslink((quiver, 'color_selected'), (color_selected, 'value'))
VBox([ipv.gcc(), size, size_selected, color, color_selected])

TypeError: quiver() got multiple values for argument 'size'