### Array
----

Điểm ưu thế của NumPy so với Python thuần là có thể mô phỏng được mảng nhiều chiều

Xem về [Mảng](https://github.com/bangoc123/learn-machine-learning-in-two-months/blob/master/python-tutorials/list.ipynb) ở Python.


![NumPy Array](https://lh3.googleusercontent.com/FupEwjNSPGKcOgrw4yczZlcnOpnqZSyp0twsldHa22YOp8b9625ywBKIcxN5iq0peY84oEdsEqEU7AFGBHTE8Xz6AJLJLvaUr_gYz8XDtWOczcdymDCN2rABzspCIUWVP0d1N2lOsfbxXYE_Vyo6gGNTtqiHTjnBAVu3s8R5_jagCSEQerMst0TUPwrvoYmWgkuhHt-umtIS52CDLQa0d57wSa8Gtd8msgRBrjMYBWsOHhhk311LhE68TkusVmWscV-WpRV87kG0tjOQW02cWMC4sxcTctymq4fXsq2cDY1YPHeRuwFrViwTABroi_O9cJefeSzKIZJ2SSaodeRmhDnoshBpDlWSb9-KPSuTs4s-kZwc64V7XhKDV0aoRZFYC1FPYXDviQML-LXk8-g16WnI3ycznJHIwHFaa5XbG0g7c1Edy6N600TUqNMpJzAleq7EON1xcUHQ0rljTt5rky5NmU6DB1yvtH54gKUK8pVG4tlA12C6shkJnl93u1xwwJKeoKmn4MD7UqZNi3-DWzLaLKrhbz4gAM8kz_FthQIa7Y0R750OMS88lNy0tQwliRpNZS5-7-g3xxriVQ1DO8dAyzOY2ntFuE-KfmPH66etxbtm9PvZnsIcp-3QIST4CNu-P4Jmv7pSSqLlErNAxwIZT1nugJN26g=w798-h189-no)

Ảnh từ [DataCamp](https://www.datacamp.com/community/tutorials/python-numpy-tutorial)

### I. Import thư viện NumPy

In [4]:
import numpy as np

### II. Khởi tạo một Array

##### 1. np.array()

##### a. Mảng 1 chiều
    - Bạn có thể liên hệ mảng 1 chiều với Vector

In [5]:
number_vector = np.array([1, 2, 3, 4])

In [7]:
number_vector.shape

(4,)

##### b. Mảng 2 chiều
    - Bạn có thể liên hệ mảng 2 chiều với ma trận 2 chiều

In [11]:
number_matrix = np.array([[1, 2, 3], [4, 5, 6]]) 

In [12]:
number_matrix

array([[1, 2, 3],
       [4, 5, 6]])

Ma trận có số hàng là 2 và số cột là 3

In [13]:
number_matrix.shape

(2, 3)

###### c. Mảng 3 chiều
    - Bạn có thể liên hệ mảng 3 chiều với ma trận 3 chiều

In [19]:
number_3D_matrix = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[1, 2, 3], [4, 5, 6]]
])

In [20]:
number_3D_matrix.shape

(2, 2, 3)

##### 2. zeros() - ones() - full()
    - Tạo ra mảng có các giá trị bằng nhau
        
        - zeros() tạo ra mảng các giá trị đều bằng 0
            - Đầu vào là shape của array dưới dạng tuple
            
        - ones() tạo ra mảng các giá trị đều bằng 1
            - Đầu vào là shape của array dưới dạng tuple
        
        - full() tạo ra mảng các giá trị bằng nhau và bằng một số cho trước
            - Đầu vào là shape của array dưới dạng tuple và giá trị cho trước

##### a. Mảng 1 chiều

np.zeros()

In [97]:
number_1D_zeros = np.zeros((7, ))

In [98]:
number_1D_zeros

array([0., 0., 0., 0., 0., 0., 0.])

np.ones()

In [99]:
number_1D_ones = np.ones((3, ))

In [100]:
number_1D_ones

array([1., 1., 1.])

np.full()

In [101]:
number_1D_sevens = np.full((6, ), 7)

In [102]:
number_1D_sevens

array([7, 7, 7, 7, 7, 7])

##### b. Mảng 2 chiều

np.zeros()

In [103]:
number_2D_zeros = np.zeros((7, 7))

In [104]:
number_2D_zeros

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

np.ones()

In [105]:
number_2D_ones = np.ones((6, 5))

In [106]:
number_2D_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

np.full()

In [107]:
number_2D_eights = np.full((8, 8), 8)

In [108]:
number_2D_eights

array([[8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8]])

##### c. Mảng 3 chiều

np.zeros()

In [109]:
number_3D_zeros = np.zeros((4, 2, 3))

In [110]:
number_3D_zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

np.ones()

In [111]:
number_3D_ones = np.ones((3, 3, 4))

In [112]:
number_3D_ones

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

np.full()

In [113]:
number_3D_twenties = np.full((3, 2, 7), 20)

In [114]:
number_3D_twenties

array([[[20, 20, 20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20, 20, 20]],

       [[20, 20, 20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20, 20, 20]],

       [[20, 20, 20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20, 20, 20]]])

##### 3. np.eye()
    - Tạo ra một ma trận đơn vị

In [115]:
np.eye((10))

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

##### 4. np.arange()

Tạo 1 Array giá trị chạy từ 0 -> 10

In [116]:
number_1D_range_10 = np.arange(10)

In [117]:
number_1D_range_10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Tạo 1 Array giá trị chạy từ 2 -> 20

In [118]:
number_1D_range_20 = np.arange(2, 10)

In [119]:
number_1D_range_20

array([2, 3, 4, 5, 6, 7, 8, 9])

Tạo 1 Array giá trị chạy từ 0 -> 30. Khoảng cách giữa các giá trị là 2.

In [120]:
number_1D_range_30 = np.arange(0, 30, 2)

In [121]:
number_1D_range_30

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

##### 5. np.random.random()
    - Tạo ra ma trận với các giá trị ngẫu nhiên

In [122]:
np.random.random((10, 5))

array([[0.2416562 , 0.07738853, 0.48258709, 0.2607063 , 0.80988611],
       [0.55631239, 0.51562934, 0.95095416, 0.59066717, 0.64751756],
       [0.42497374, 0.11966676, 0.82407811, 0.80352517, 0.12991066],
       [0.24715683, 0.29748386, 0.26677741, 0.02107929, 0.21032197],
       [0.18406292, 0.86952751, 0.63418968, 0.07755376, 0.50483528],
       [0.87096656, 0.04928014, 0.65223194, 0.63928117, 0.4443445 ],
       [0.19519642, 0.55467875, 0.57888658, 0.01509584, 0.50863294],
       [0.09283353, 0.54861298, 0.76249622, 0.70733076, 0.1887354 ],
       [0.82271984, 0.53933904, 0.20685336, 0.42698788, 0.37528835],
       [0.6270273 , 0.66702909, 0.69230398, 0.22863118, 0.63605925]])