## Phép lặp (Iterating)
----

Xem thêm tại [Iterating](https://docs.scipy.org/doc/numpy/reference/generated/numpy.nditer.html)

### I. Lặp qua các phần tử

##### 1. Mảng một chiều

In [25]:
import numpy as np

In [26]:
numbers_1D = np.arange(10)

In [27]:
numbers_1D

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
for item in np.nditer(numbers_1D):
    print item

0
1
2
3
4
5
6
7
8
9


##### 2. Mảng hai chiều

In [7]:
numbers_2D = np.random.random((3, 2))

In [8]:
numbers_2D

array([[0.50255155, 0.14477689],
       [0.25697343, 0.26250991],
       [0.14294119, 0.86949863]])

In [9]:
for item in np.nditer(numbers_2D):
    print item

0.5025515528886214
0.14477689330268562
0.25697343316107546
0.26250990807465013
0.14294119185276755
0.8694986286997518


##### 3. Mảng ba chiều

In [29]:
numbers_3D = np.random.random((2, 3, 2))

In [30]:
numbers_3D

array([[[0.60994814, 0.02299673],
        [0.56888235, 0.17304354],
        [0.18849752, 0.6025226 ]],

       [[0.64390825, 0.50995602],
        [0.98812906, 0.5546137 ],
        [0.28536714, 0.01933138]]])

In [31]:
for item in np.nditer(numbers_3D):
    print item

0.6099481441938507
0.022996726612215745
0.5688823546426007
0.17304354432564684
0.18849752347038662
0.6025226030053162
0.6439082520107483
0.50995602226168
0.9881290561467033
0.5546137031592939
0.28536714183460965
0.01933137707226673


##### 4. Thay đổi giá trị trong quá trình lặp

In [33]:
numbers = np.arange(7)

In [34]:
numbers

array([0, 1, 2, 3, 4, 5, 6])

In [35]:
# Bình phương mỗi phần tử
# Chú ý: Thêm cờ op_flags = ['readwrite'] để bật chế độ có thể thay đổi các phần tử trong mảng
for item in np.nditer(numbers, op_flags = ['readwrite']):
    item[...] = item ** 2

In [36]:
numbers

array([ 0,  1,  4,  9, 16, 25, 36])

### II. Lặp qua dòng

In [40]:
float_2D = np.random.random((2, 2))

In [41]:
float_2D

array([[0.93482515, 0.51820666],
       [0.19629551, 0.01829495]])

In [53]:
for x in np.nditer(float_2D, flags = ['external_loop'], order = 'F'):
   print x,

[0.93482515 0.19629551] [0.51820666 0.01829495]


In [54]:
for x in np.nditer(float_2D, flags = ['external_loop'], order = 'C'):
   print x,

[0.93482515 0.51820666 0.19629551 0.01829495]
