## Thay đổi - Manipulation
----

Xem thêm về [Manipulation](https://www.tutorialspoint.com/numpy/numpy_array_manipulation.htm)

## I. Thay đổi kích thước mảng

##### 1. reshape()
Trả về mảng mới với kích cỡ được thay đổi

In [13]:
import numpy as np

In [14]:
numbers_2D = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

In [15]:
numbers_2D.shape

(2, 4)

Trả về mảng mới 3 chiều (2, 2, 2) từ mảng 2 chiều (2, 4)

In [18]:
numbers_3D = numbers_2D.reshape(2, 2, 2)

In [20]:
numbers_3D

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [19]:
numbers_3D.shape

(2, 2, 2)

##### 2. flatten()
Trả về mảng được duỗi còn 1 chiều

In [21]:
numbers = np.random.random((3, 3, 3))

In [22]:
numbers

array([[[9.50066461e-01, 9.01003882e-01, 7.84720479e-01],
        [9.47879738e-01, 1.35717696e-04, 5.07770033e-01],
        [3.44713769e-02, 2.59649993e-01, 1.91719024e-01]],

       [[7.58448374e-01, 5.60712235e-02, 4.01477814e-01],
        [1.45508565e-01, 3.05456872e-01, 9.78449095e-01],
        [4.51628284e-01, 1.67485426e-01, 9.31215167e-01]],

       [[2.62117961e-01, 5.17461074e-01, 2.50675234e-01],
        [9.57124891e-01, 9.73925297e-01, 1.86436315e-01],
        [8.37553296e-01, 6.90010658e-01, 4.94900385e-01]]])

In [25]:
numbers.shape

(3, 3, 3)

In [27]:
flattened_numbers = numbers.flatten()

In [28]:
flattened_numbers.shape

(27,)

##### 3. expand_dims()
Trả về mảng mới được thêm chiều

In [45]:
numbers_2D = np.array(([1,2],[3,4])) 

In [50]:
numbers_2D.shape

(2, 2)

Mở rộng theo dòng axis=0

In [57]:
numbers_3D_axis_0 = np.expand_dims(numbers_2D, axis=0)

In [58]:
numbers_3D_axis_0.shape

(1, 2, 2)

Mở rộng theo cột axis=1

In [55]:
numbers_3D_axis_1 = np.expand_dims(numbers_2D, axis=1)

In [56]:
numbers_3D.shape

(2, 1, 2)

##### 4. squeeze()
Trả về mảng mới được giảm chiều

In [67]:
numbers_3D = np.random.random((1, 20, 20))

In [68]:
numbers_2D_axis_0 = np.squeeze(numbers_3D, axis=0)

In [69]:
numbers_2D_axis_0.shape

(20, 20)

### II. Chuyển vị

Xem lại chuyển vị ở phần [kiến thức toán học](https://github.com/bangoc123/learn-machine-learning-in-two-months/#1-ki%E1%BA%BFn-th%E1%BB%A9c-to%C3%A1n-h%E1%BB%8Dc-c%E1%BA%A7n-thi%E1%BA%BFt)

![transpose](https://lh3.googleusercontent.com/9a1m0a1kozsZtPgffI2fAsgm2nnRymGYVgp3EXjXnHTZqBe-O5IT-WLT4N1r_2HsK_vP16ssazkAQvmh4ccv1-rMCZDA5f1llpvkqZFC7_ZFmNpVXXNkKHhenen0DXfzS1NqauBRiThtxxrnqvs6DjiHNv3o6z9QPOTuq19cWz9TBU2mkJKEMihglnKdKlNJa2l05WeBmJwAcpjwSQft5jlrn6kr9X782n9jPuC32pE7SOtIEzVSdV_DoRZMonrOnRRGsiz1bJFSumC9gaAaTx-kqGQbf6sKU3avjzNe6Elyg36MkwEfWAbCR9kMGXZ9shkgh41ymTLCNfqsqWuX2DrcfXbwNCjwj17IHeAeITYJoIP-W1lEk0yC7faQUmUh_OSpxG2Km5GFVQQxEj1SeNOW-k0jLyzjYuoyhLX3AGEYaHuDk81a4_HFRpg9fAD6aOGkQHNPghQrA2BQW9FgFK3pL6JDqtbuGQd9mz-KIjHSDTBm1OpQwxXMAnfYr6V0Jq4fULBKCCd96IZC_eJRxIFY_Za_cegK7FYIla9s7ggBg_n7zlAF7V9-BFJcZ9eVl6-_8UhUT20xdSkWERnqwtGwiikEDf5mbzg9iNjktPswaqqd3Y-JupOCH8KdLF5MgXAhexeb6SlWAuu55gy4ucR62iRZj7tan5fjyBlcT-ZqHOhZEXSxGoqEcQ=w800-h400-no)

In [30]:
numbers_2D = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

In [31]:
numbers_2D

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [32]:
numbers_2D.shape

(2, 4)

In [38]:
transposed_numbers_1 = numbers_2D.T

In [44]:
transposed_numbers_1

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [40]:
transposed_numbers_1.shape

(4, 2)

Cách tương tự

In [41]:
# Tương đương với
transposed_numbers_2 = np.transpose(numbers_2D)

In [43]:
transposed_numbers_2.shape

(4, 2)